title: Career of Wouter 
author: Wouter Vanhoutte
email: vanhouttewouter@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site gives an overview of the career of Wouter Vanhoutte,
  experienced SAP Analytics and Planning Consultant. He specializes
  in the implementation of the SAP Business Planning & Consolidation (BPC),
  SAP Analytics Cloud (SAC) , Business Warehouse (BW) and HANA database
  development.

# social links
twitter_username: vanhouttewouter # DO NOT include the @ character, or else the build will fail!
github_username:  wouter-stack # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
